### ISSUE TITLE
Firefox not Working

### ISSUE THREAD

**Issue by luizcavalieri** [tonystar/float-label-css#16]
Hi,

I'm I doing something wrong or the library doesn't work with Firefox?

![screen shot 2017-02-23 at 1 01 07 pm](https://cloud.githubusercontent.com/assets/7554530/23241623/35b9b9d4-f9c8-11e6-8381-5c8793effcfa.png)
![screen shot 2017-02-23 at 1 01 02 pm](https://cloud.githubusercontent.com/assets/7554530/23241624/35c4aa88-f9c8-11e6-8df8-4ca73873dd1b.png)

**Comment by DSchuyt** [comment]
Firefox does work. However, 1 styling rule is left out. The placeholders are currently hidden with **::-webkit-input-placeholder**.

Try adding the following rule to hide the placeholders in FF too:
`.has-float-label input:placeholder-shown:not(:focus)::-moz-placeholder,.has-float-label select:placeholder-shown:not(:focus)::-moz-placeholder { opacity:0; }`

**Comment by tonystar** [comment]
Thanks @luizcavalieri for reporting, @DSchuyt for suggestion!

I can confirm a bug in FF/Win, and not in FF/MacOS.

**Comment by tonystar** [comment]
Fixed in demo: https://codepen.io/tonystar/pen/JRLaKw. Patch is comming.

**Comment by syrianadus** [comment]
is the fix also for IE ? what was your workaround for ::placeholder?

**Comment by tonystar** [comment]
@syrianadus it was not a workaround. it was "unhardcode". so now it can be compiled automatically to:
```css
.has-float-label input::-webkit-input-placeholder, .has-float-label select::-webkit-input-placeholder, .has-float-label textarea::-webkit-input-placeholder {
  opacity: 1;
  -webkit-transition: all .2s;
          transition: all .2s;
}
.has-float-label input::-moz-placeholder, .has-float-label select::-moz-placeholder, .has-float-label textarea::-moz-placeholder {
  opacity: 1;
  transition: all .2s;
}
.has-float-label input:-ms-input-placeholder, .has-float-label select:-ms-input-placeholder, .has-float-label textarea:-ms-input-placeholder {
  opacity: 1;
  transition: all .2s;
}
.has-float-label input::placeholder, .has-float-label select::placeholder, .has-float-label textarea::placeholder {
  opacity: 1;
  -webkit-transition: all .2s;
          transition: all .2s;
}
```

Unfortunately there is no pure-CSS way for IE. Because: http://caniuse.com/css-placeholder-shown/embed/.
